import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'
import { Toaster } from "@/components/ui/toaster";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Zoom Clone",
  description: "Generated by Almaaz",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<ClerkProvider 
appearance={{variables:{
  colorText:'#fff',
  colorPrimary:'#0E78f9',
  colorBackground:'#1c1f2e',
  colorInputBackground:'#252a41'
}}}
>
      <body className={`${inter.className} bg-dark-2`}>{children}</body>
<Toaster/>
</ClerkProvider>
    </html>
  );
}
